<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jeu du pendu en PHP</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="./assets/css/styles.css">
</head>
<body>
    <div class="container">
        <div class="row mt-5">
            <aside class="col-4 text-center">
                <img src="./assets/images/logo-zombie.svg" alt="Bienvenue sur le jeu du pendu" class="w-50">
                <img src="./assets/images/pendu-zombie/<?=$nbErrors?>.svg" alt="Potence du jeu du pendu">
            </aside>
            <div class="col-8">
                <header class="text-center">

                        <?php if ($lost) : ?>
                            <h1 class='lost'>Perdu&nbsp;!</h1>
                            <p>Il fallait trouver <strong><?=DICO[$index]?></strong> </p>
                        <?php elseif ($won) : ?>
                            <h1 class='win'>Gagné&nbsp;!</h1>
                        <?php else : ?>
                            <h1>À vous !</h1>
                            <p class="mt-3">Essayez de trouver le mot ci-dessous en proposant une lettre à la fois.<br>
                            Attention, vous n'avez le droit qu'à <?=6-$nbErrors?> erreur(s).</p>
                        <?php endif ?>
                </header>
                <main>
                    <section id="play-area">
                        
                        <div class="row">
                            <div class="col-12 text-center">
                                <h5 class="clue <?=$clueCSSClass?>"><?=$clueString?></h5>
                            </div>
                        </div>

                            <form action="index.php" method="post">
                                <input type="hidden" name="index" value="<?=$index?>">
                                <input type="hidden" name="propositions" value="<?=$propositions?>">

                                <?php if (!$won && !$lost) : ?>
                                    <div class="row mt-5">
                                        <div class="col-4 text-end">
                                            <label for="letter" class="form-label">Saisissez une lettre&nbsp;:</label>
                                        </div>
                                        <div class="col-3">
                                            <input type="text" class="form-control" name="lettre" id="lettre" maxlength="1" autofocus>
                                        </div>
                                        <div class="col-3">
                                            <input type="submit" class="btn btn-primary w-100">
                                        </div>
                                    </div> 
                                <?php endif?>

                            </form>
                            
                            <?php if ($propositions != '') : ?>
                                <div class="row mt-3">
                                    <div class="col-4 text-end">
                                        <label class="form-label">Déjà proposées&nbsp;:</label>
                                    </div>
                                    <div class="col-3">
                                        <h5 class="propositions"><?=$propositions?></h5>
                                    </div>
                                </div>  
                            <?php endif ?> 

                        <div class="row">
                            <div class="col-3 mt-3">
                                <a href="index.php" class="btn btn-secondary w-100">Rejouer</a>
                            </div>
                            <div class="col-3 offset-6">

                                <?php if ($won) : ?>
                                    <img src="./assets/images/victoire.svg" alt="" class="img-fluid">
                                <?php elseif ($lost) : ?>
                                    <img src="./assets/images/perdu.svg" alt="" class="img-fluid">
                                <?php endif ?>

                            </div>
                        </div>
                    </section>
                </main>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>